### ISSUE TITLE
archive-server with mongodb in a different server

### ISSUE THREAD

**Issue by leandrosouza** [tsuru/tsuru#1095]
When running mongodb in a different server happen this error:

```
$git push tsuru master
Counting objects: 5650, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2445/2445), done.
Writing objects: 100% (5650/5650), 3.46 MiB | 0 bytes/s, done.
Total 5650 (delta 2757), reused 5650 (delta 2757)
remote: Traceback (most recent call last):
remote:   File "<stdin>", line 2, in <module>
remote:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
remote:     return _default_decoder.decode(s)
remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
remote:     raise ValueError("No JSON object could be decoded")
remote: ValueError: No JSON object could be decoded
```

**Comment by leandrosouza** [comment]
post-receive debug

remote: +++ curl -sNd 'path=/var/lib/gandalf/repositories/tsuru-dashboard.git&refid=7f6f0aa1a7ef65e995f6f03b0e5689cfec886fc2' http://127.0.0.1:3131/
remote: ++ result='no reachable servers'
remote: ++ python
remote: Traceback (most recent call last):
remote:   File "<stdin>", line 2, in <module>
remote:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
remote:     return _default_decoder.decode(s)
remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
remote:     raise ValueError("No JSON object could be decoded")
remote: ValueError: No JSON object could be decoded
remote: + archive_id=

**Comment by leandrosouza** [comment]
Thanks @fsouza It's work for me.
