### ISSUE TITLE
service-instance-remove crashing when `-u` option is passed

### ISSUE THREAD

**Issue by etandel** [tsuru/tsuru#1445]
When removing a bound instance from a service by using the `-u` parameter:

``` bash
tsuru service-instance-remove docker redis-staging -u
```

I get the following crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43c440]

goroutine 1 [running]:
panic(0x9d8f00, 0xc82000e120)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
main.removeServiceInstanceWithUnbind(0xc8201c78b0, 0xc8201c7900, 0x0, 0x0)
    /Users/andrews/.go/src/github.com/tsuru/tsuru-client/tsuru/services.go:628 +0x640
main.(*serviceInstanceRemove).Run(0xc8201c2050, 0xc8201c78b0, 0xc8201c7900, 0x0, 0x0)
    /Users/andrews/.go/src/github.com/tsuru/tsuru-client/tsuru/services.go:655 +0x3a2
github.com/tsuru/tsuru-client/vendor/github.com/tsuru/tsuru/cmd.(*Manager).Run(0xc8201c4000, 0xc8201d6360, 0x2, 0x2)
    /Users/andrews/.go/src/github.com/tsuru/tsuru-client/vendor/github.com/tsuru/tsuru/cmd/cmd.go:233 +0x198e
main.main()
    /Users/andrews/.go/src/github.com/tsuru/tsuru-client/tsuru/main.go:108 +0xba
```

However, it all works out when I do the steps separately:

``` bash
tsuru service-instance-unbind docker redis-staging -a api-staging
tsuru service-instance-remove docker redis-staging
```

**Comment by etandel** [comment]
BTW, I'm using the tsuru version 1.0.1., precompiled.

**Comment by ArxdSilva** [comment]
@etandel could you please try again to reproduce this behavior? I did the same steps and could not get in the same results, maybe It was fixed and we did not give any feedback here.
