### ISSUE TITLE
invalid response from tsuru API: You must provide a valid Authorization header

### ISSUE THREAD

**Issue by vmalaga** [tsuru/tsuru#1473]
Hello.

After upgrade our tsuru environment we have a lot of apps that can't start with this message:

```
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: Traceback (most recent call last):
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: File "/usr/local/bin/tsuru_unit_agent", line 9, in <module>
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: envs = client.register_unit(args.app_name)
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 13, in run_action
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: raise Exception("invalid response {} - {}".format(response.status_code, response.text))
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 56, in main
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: actions[args.action](args)
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: load_entry_point('tsuru-unit-agent==0.3.7', 'console_scripts', 'tsuru_unit_agent')()
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/client.py", line 30, in register_unit
2016-10-04 03:15:12 +0200 [][9d00b2fbf732]: Exception: invalid response 401 - You must provide a valid Authorization header
```

I have not update any token or parameter , only tsurud migrate at the end of the process.
if make app-restart i got the same message.

not on all apps are afected, only on 15 of 60 apps and i have done to verify a complete app deploy and works fine

**Comment by vmalaga** [comment]
with debug on the  pre-receive hook I see the error is produced by curl trying to athenticate with tsuru

```
remote: + curl -H 'Authorization: bearer bf1181bb84ef7fe24c8f035cf3941b3843450580' -d 'archive-url=http://172.16.70.100:3232/?id=72343cd1c23b9f2c6a49251f0f54f5b78f552a7b55096bf7c834daddbf88cbb2b820258daa95b1585c13469a24ca18383bea7d3c4337b3f97beefa2c8c59ca6e&commit=e534dd4666612544ff22a1d991376037495a08a2&user=admin@qdqmedia.com' -s -N http://172.16.70.100:8080/apps/billing/repository/clone
```

Also I can see the value of bearer comes from TSURU_TOKEN variable

```
remote: + export TSURU_TOKEN=bf1181bb84ef7fe24c8f035cf3941b3843450580
remote: + TSURU_TOKEN=bf1181bb84ef7fe24c8f035cf3941b3843450580
```

- Is it possible that TSURU TOKEN have a wrong value? 
- where came from TSURU_TOKEN?
- Can I regenerate this token with a valid value ?

[tsuru.txt](https://github.com/tsuru/tsuru/files/507898/tsuru.txt)

**Comment by cezarsa** [comment]
The problem seems to be related to app tokens expiring. Ever since tsuru 0.12 (https://github.com/tsuru/tsuru/commit/a43447bced5ca0339e2dfd9ee331004ed3638aa2) app tokens do not expire anymore. However, if you have some apps created in a previous version it's possible that they have an expiration date set in mongodb. To fix this you can simply run this command in your mongodb console:
```
db.tokens.update({appname: {$ne: ""}}, {$set: {expires: 0}}, {multi: true})
```
Sorry for the trouble.

**Comment by vmalaga** [comment]
Hi @cezarsa 

yes is possible, more of this apps was created on 2015-04-xx and some of then never updated since 2015.
I have 2 type of tokens on mongo, one with appname but useremail empty and other with useremail but appname empty
```
{
    "_id": ObjectID("552b01088fd7c95a3b301712"),
    "token": "cb0aa995a93b305d96d973c33ca8c970ef109364",
    "creation": ISODate("2015-04-12T23:34:32.911Z"),
    "expires": "31536000000000000",
    "useremail": "",
    "appname": "service-mysql"
}
{
    "_id": ObjectID("553182208fd7c95a3b36a6d0"),
    "token": "32e50ab651bcb454dcaab4cdd9c5c2b62c7968e9",
    "creation": ISODate("2015-04-17T21:58:56.184Z"),
    "expires": 604800000000000,
    "useremail": "vmalaga@qdqmedia.com",
    "appname": ""
}
```
But I can see on the last apps created the expires: 0 
I am going to set it on all apps.
```
{
    "_id": ObjectID("56026ecf6fafc954a6c1b208"),
    "token": "8185ba5c8706d020cc93684e1003769c872e59e5",
    "creation": ISODate("2016-09-23T09:20:15.978Z"),
    "expires": 0,
    "useremail": "",
    "appname": "landerdash"
}
```

Regards

**Comment by cezarsa** [comment]
Yeah, glad this fixes your problem and sorry for the trouble. (I've also edited your comment to remove the token values just to be safe 😃)
